// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydzywcrqbnpvwfllsadq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkenl3Y3JxYm5wdndmbGxzYWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjIzNDIsImV4cCI6MjA3MzY5ODM0Mn0.isNmu9ceQ0_FWtpBbyZDq3UeS_JshJENTL7SZwi5Wbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});